"""initial migration

Revision ID: 6efa45c09259
Revises: 
Create Date: 2023-05-19 04:24:05.606988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efa45c09259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=True),
    sa.Column('definitions', sa.JSON(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
