"""add language field and word_lang unique pair

Revision ID: 87e82eaf9253
Revises: 6efa45c09259
Create Date: 2023-05-21 21:29:42.835644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e82eaf9253'
down_revision = '6efa45c09259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('source_language', sa.String(length=2), nullable=True))
    op.add_column('words', sa.Column('translate_language', sa.String(length=2), nullable=True))
    op.drop_constraint('uq_word_language', 'words', type_='unique')
    op.create_unique_constraint('uq_word_language', 'words', ['word', 'source_language', 'translate_language'])
    op.drop_column('words', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint('uq_word_language', 'words', type_='unique')
    op.create_unique_constraint('uq_word_language', 'words', ['word', 'language'])
    op.drop_column('words', 'translate_language')
    op.drop_column('words', 'source_language')
    # ### end Alembic commands ###
